name: rocm

on:
  pull_request:
    # run CI only if rocm directory or rocm sub-directories receive updates
    paths:
      - 'src/components/rocm/**'
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  component_tests:
    strategy:
      matrix:
        component: [rocm]
        debug: [yes, no] 
        shlib: [with, without]
      fail-fast: false
    runs-on: [self-hosted, gpu_amd]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: rocm component tests
        run: .github/workflows_scripts/ci_individual_component.sh ${{matrix.component}} ${{matrix.debug}} ${{matrix.shlib}}
